version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo:3.7
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  # postgres:
  #   container_name: postgres
  #   env_file: .env
  #   image: postgres
  #   ports:
  #     - '5432:5432'
  #   restart: unless-stopped
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

volumes:
  mongo:
  # postgres-data: {}
